//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealProduct
    {
        public int id { get; set; }
        public Nullable<int> fk_deal_product_dealproduct { get; set; }
        public Nullable<int> fk_product_product_dealproduct { get; set; }
        public Nullable<double> quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
