//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DealProducts = new HashSet<DealProduct>();
            this.DealProducts1 = new HashSet<DealProduct>();
        }
    
        public int id { get; set; }
        public string barcode { get; set; }
        public Nullable<double> carrycost { get; set; }
        public Nullable<double> discount { get; set; }
        public string name { get; set; }
        public Nullable<double> purchaseprice { get; set; }
        public Nullable<bool> purchaseactive { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> saleprice { get; set; }
        public Nullable<bool> saleactive { get; set; }
        public string type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealProduct> DealProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealProduct> DealProducts1 { get; set; }
    }
}
