//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Deposit
    {
        public int Id { get; set; }
        public Nullable<double> Ammount { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DatenTime { get; set; }
        public Nullable<int> DepositHead_Id { get; set; }
    
        public virtual tbl_DepositHead tbl_DepositHead { get; set; }
    }
}
