//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FinanceChart
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> Sale { get; set; }
        public Nullable<double> Delivery { get; set; }
        public Nullable<double> TotalSale { get; set; }
        public Nullable<double> TotalCash { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> Expence { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
    }
}
