//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Staff()
        {
            this.tbl_DeliveryQueue = new HashSet<tbl_DeliveryQueue>();
            this.tbl_Sale = new HashSet<tbl_Sale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CNIC { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<int> DutyStart { get; set; }
        public Nullable<int> DutyEnd { get; set; }
        public string Comment { get; set; }
        public Nullable<int> StaffCategory_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DeliveryQueue> tbl_DeliveryQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sale> tbl_Sale { get; set; }
        public virtual tbl_StaffCategory tbl_StaffCategory { get; set; }
    }
}
