//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DetuctInventory
    {
        public int Id { get; set; }
        public Nullable<int> FoodItem_Id { get; set; }
        public Nullable<double> DeductedQuantity { get; set; }
        public Nullable<int> KitchenInventory_id { get; set; }
    
        public virtual tbl_KitchenInventory tbl_KitchenInventory { get; set; }
    }
}
