//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KitchenInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KitchenInventory()
        {
            this.tbl_DetuctInventory = new HashSet<tbl_DetuctInventory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> MinimumQuantity { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> KitchenInventoryCategory_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DetuctInventory> tbl_DetuctInventory { get; set; }
        public virtual tbl_KitchenInventoryCategory tbl_KitchenInventoryCategory { get; set; }
    }
}
