//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeliveryQueue
    {
        public int Id { get; set; }
        public Nullable<bool> Delivered { get; set; }
        public Nullable<System.DateTime> DatenTime { get; set; }
        public Nullable<int> Sale_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> DeliveryBoyId { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_Staff tbl_Staff { get; set; }
        public virtual tbl_FoodItemCategory tbl_FoodItemCategory { get; set; }
        public virtual tbl_Sale tbl_Sale { get; set; }
    }
}
