//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sale()
        {
            this.tbl_DeliveryQueue = new HashSet<tbl_DeliveryQueue>();
            this.tbl_SaleItem = new HashSet<tbl_SaleItem>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> SaleType { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Staff_id { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DeliveryQueue> tbl_DeliveryQueue { get; set; }
        public virtual tbl_Staff tbl_Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleItem> tbl_SaleItem { get; set; }
    }
}
